"""add unique constraint on company name and labels_size

Revision ID: 50048417651e
Revises: dc9e3cea8bba
Create Date: 2026-02-10 20:13:44.621616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50048417651e'
down_revision = 'dc9e3cea8bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_company_name_labels_size', ['name', 'labels_size'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('uq_company_name_labels_size', type_='unique')

    # ### end Alembic commands ###
