"""fix lyrics.id: add identity sequence and primary key

The initial migration added lyrics.id as a plain NOT NULL integer without a
sequence/default and without a primary key constraint, so inserts failed with
a NotNullViolation on id. This makes id a GENERATED BY DEFAULT AS IDENTITY
primary key, matching the Lyric model.

Revision ID: a1f3c7d29e10
Revises: 50048417651e
Create Date: 2026-06-14 09:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f3c7d29e10'
down_revision = '50048417651e'
branch_labels = None
depends_on = None


def upgrade():
    # Make id an identity column (Postgres assigns values on insert) and the PK.
    op.execute(
        'ALTER TABLE lyrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY'
    )
    op.create_primary_key('pk_lyrics', 'lyrics', ['id'])
    # Align the identity sequence with any existing rows.
    op.execute(
        "SELECT setval(pg_get_serial_sequence('lyrics', 'id'), "
        "COALESCE((SELECT MAX(id) FROM lyrics), 0) + 1, false)"
    )


def downgrade():
    op.drop_constraint('pk_lyrics', 'lyrics', type_='primary')
    op.execute('ALTER TABLE lyrics ALTER COLUMN id DROP IDENTITY IF EXISTS')
