"""change Disk table

Revision ID: dc9e3cea8bba
Revises: 85066d902cd1
Create Date: 2026-02-10 07:44:58.362053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9e3cea8bba'
down_revision = '85066d902cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_disks_company_id'), ['company_id'], unique=False)
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['company_id'])
        batch_op.drop_column('company')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_disks_company_id'))
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
