"""Initial Migration

Revision ID: bc6a644d90c9
Revises: 
Create Date: 2026-01-27 10:53:45.223039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6a644d90c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('old_songs')
    op.drop_table('peopletofix')
    op.drop_table('diskssongs')
    with op.batch_alter_table('disks', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               nullable=False)
        batch_op.alter_column('company',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('size',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('sakisid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('disks_pk'), type_='unique')
        batch_op.drop_constraint(batch_op.f('disks_pk_2'), type_='unique')
        batch_op.drop_constraint(batch_op.f('disks_pk_3'), type_='unique')
        batch_op.create_index(batch_op.f('ix_disks_name'), ['name'], unique=False)
        batch_op.drop_column('companyid')

    with op.batch_alter_table('lyrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('song_id', sa.Integer(), nullable=False))
        batch_op.alter_column('lyric',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_lyrics_song_id'), ['song_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('lyrics_songs_songid_fk'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'songs', ['song_id'], ['song_id'])
        batch_op.drop_column('lyricsid')
        batch_op.drop_column('songid')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('people_pk_2'), type_='unique')
        batch_op.create_index(batch_op.f('ix_people_name'), ['name'], unique=False)

    with op.batch_alter_table('peoplesongs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('song_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('isComposer', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('isSongwriter', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('isSinger', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('isMusician', sa.Boolean(), nullable=False))
        batch_op.drop_constraint(batch_op.f('peoplesongs_people_peopleid_fk'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('peoplesongs_songs_songid_fk'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['person_id'], ['person_id'])
        batch_op.create_foreign_key(None, 'songs', ['song_id'], ['song_id'])
        batch_op.drop_column('peopleid')
        batch_op.drop_column('ismusician')
        batch_op.drop_column('songid')
        batch_op.drop_column('issinger')
        batch_op.drop_column('iscomposer')
        batch_op.drop_column('issongwriter')

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('songs_pk_2'), type_='unique')
        batch_op.create_index(batch_op.f('ix_songs_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_songs_title'))
        batch_op.create_unique_constraint(batch_op.f('songs_pk_2'), ['title'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('peoplesongs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issongwriter', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('iscomposer', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('issinger', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('songid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ismusician', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('peopleid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('peoplesongs_songs_songid_fk'), 'songs', ['songid'], ['song_id'])
        batch_op.create_foreign_key(batch_op.f('peoplesongs_people_peopleid_fk'), 'people', ['peopleid'], ['person_id'])
        batch_op.drop_column('isMusician')
        batch_op.drop_column('isSinger')
        batch_op.drop_column('isSongwriter')
        batch_op.drop_column('isComposer')
        batch_op.drop_column('song_id')
        batch_op.drop_column('person_id')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_name'))
        batch_op.create_unique_constraint(batch_op.f('people_pk_2'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('lyrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('songid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lyricsid', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lyrics_songs_songid_fk'), 'songs', ['songid'], ['song_id'])
        batch_op.drop_index(batch_op.f('ix_lyrics_song_id'))
        batch_op.alter_column('lyric',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('song_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('disks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('companyid', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_disks_name'))
        batch_op.create_unique_constraint(batch_op.f('disks_pk_3'), ['company', 'companyid'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('disks_pk_2'), ['sakisid'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('disks_pk'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('sakisid',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('size',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('company',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               nullable=True)

    op.create_table('diskssongs',
    sa.Column('diskid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('songid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['diskid'], ['disks.disk_id'], name=op.f('diskssongs_disks_diskid_fk')),
    sa.ForeignKeyConstraint(['songid'], ['songs.song_id'], name=op.f('diskssongs_songs_songid_fk')),
    sa.UniqueConstraint('songid', 'diskid', name=op.f('diskssongs_pk'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='a junction table between songs and disks'
    )
    op.create_table('peopletofix',
    sa.Column('peopleid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_composer', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_writer', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_instrumentalist', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_singer', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('peopleid', name=op.f('peopletofix_pk'))
    )
    op.create_table('old_songs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('composer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('writer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lyrics', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bibliography', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('old_songs_pk'))
    )
    # ### end Alembic commands ###
