"""Add timestamps to models

Revision ID: bf32b2a4f159
Revises: bc6a644d90c9
Create Date: 2026-02-02 11:19:44.366258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf32b2a4f159'
down_revision = 'bc6a644d90c9'
branch_labels = None
depends_on = None


from datetime import datetime, timezone

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    now = datetime.now(timezone.utc)
    
    op.add_column('disks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('disks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute(f"UPDATE disks SET created_at = '{now}', updated_at = '{now}'")
    op.alter_column('disks', 'created_at', nullable=False)
    op.alter_column('disks', 'updated_at', nullable=False)

    op.add_column('lyrics', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('lyrics', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute(f"UPDATE lyrics SET created_at = '{now}', updated_at = '{now}'")
    op.alter_column('lyrics', 'created_at', nullable=False)
    op.alter_column('lyrics', 'updated_at', nullable=False)

    op.add_column('people', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('people', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute(f"UPDATE people SET created_at = '{now}', updated_at = '{now}'")
    op.alter_column('people', 'created_at', nullable=False)
    op.alter_column('people', 'updated_at', nullable=False)

    op.add_column('peoplesongs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('peoplesongs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute(f"UPDATE peoplesongs SET created_at = '{now}', updated_at = '{now}'")
    op.alter_column('peoplesongs', 'created_at', nullable=False)
    op.alter_column('peoplesongs', 'updated_at', nullable=False)

    op.add_column('songs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('songs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute(f"UPDATE songs SET created_at = '{now}', updated_at = '{now}'")
    op.alter_column('songs', 'created_at', nullable=False)
    op.alter_column('songs', 'updated_at', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('peoplesongs', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('lyrics', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('disks', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
