"""baseline schema from models

Revision ID: e0f0808b9f6a
Revises: 
Create Date: 2026-06-22 19:07:10.528880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f0808b9f6a'
down_revision = None
branch_labels = None
depends_on = None

# (index name, table, column) for every column searched with ILIKE in /search.
TRGM_INDEXES = [
    ('ix_trgm_songs_title', 'songs', 'title'),
    ('ix_trgm_songs_notes', 'songs', 'notes'),
    ('ix_trgm_disks_name', 'disks', 'name'),
    ('ix_trgm_disks_notes', 'disks', 'notes'),
    ('ix_trgm_disks_sakisid', 'disks', 'sakisid'),
    ('ix_trgm_people_name', 'people', 'name'),
    ('ix_trgm_people_notes', 'people', 'notes'),
    ('ix_trgm_companies_name', 'companies', 'name'),
    ('ix_trgm_companies_info', 'companies', 'info'),
    ('ix_trgm_disklabels_label', 'disklabels', 'label'),
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('labels_size', sa.Integer(), nullable=False),
    sa.Column('info', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('name', 'labels_size', name='uq_company_name_labels_size')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)

    op.create_table('people',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('person_id'),
    sa.UniqueConstraint('name', name='uq_people_name')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_name'), ['name'], unique=False)

    op.create_table('songs',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('lyrics', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('song_id')
    )
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_songs_title'), ['title'], unique=False)

    op.create_table('disklabels',
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.TEXT(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('label_id')
    )
    with op.batch_alter_table('disklabels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disklabels_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disklabels_label'), ['label'], unique=False)

    op.create_table('disks',
    sa.Column('disk_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('sakisid', sa.String(length=250), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('disk_id'),
    sa.UniqueConstraint('name', name='uq_disks_name')
    )
    with op.batch_alter_table('disks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disks_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disks_name'), ['name'], unique=False)

    op.create_table('peoplesongs',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('isComposer', sa.Boolean(), nullable=False),
    sa.Column('isSongwriter', sa.Boolean(), nullable=False),
    sa.Column('isSinger', sa.Boolean(), nullable=False),
    sa.Column('isMusician', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.person_id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.song_id'], ),
    sa.PrimaryKeyConstraint('person_id', 'song_id')
    )
    op.create_table('discsongs',
    sa.Column('diskid', sa.Integer(), nullable=False),
    sa.Column('songid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diskid'], ['disks.disk_id'], ),
    sa.ForeignKeyConstraint(['songid'], ['songs.song_id'], ),
    sa.PrimaryKeyConstraint('diskid', 'songid')
    )
    # ### end Alembic commands ###

    # pg_trgm GIN indexes for fast ILIKE substring search ('%term%') used by
    # /search. Not expressible in the models, so created explicitly here.
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    for name, table, column in TRGM_INDEXES:
        op.execute(
            f'CREATE INDEX IF NOT EXISTS {name} ON {table} '
            f'USING gin ({column} gin_trgm_ops)'
        )


def downgrade():
    for name, _table, _column in TRGM_INDEXES:
        op.execute(f'DROP INDEX IF EXISTS {name}')
    # Leave the pg_trgm extension in place; other objects may rely on it.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discsongs')
    op.drop_table('peoplesongs')
    with op.batch_alter_table('disks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disks_name'))
        batch_op.drop_index(batch_op.f('ix_disks_company_id'))

    op.drop_table('disks')
    with op.batch_alter_table('disklabels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disklabels_label'))
        batch_op.drop_index(batch_op.f('ix_disklabels_company_id'))

    op.drop_table('disklabels')
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_songs_title'))

    op.drop_table('songs')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_name'))

    op.drop_table('people')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_name'))

    op.drop_table('companies')
    # ### end Alembic commands ###
